const actionType = {
    GET_HOME: 'GET_HOME',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_DURATION_SONG: 'SET_DURATION_SONG',
    // music
    PLAY_MUSIC: 'PLAY_MUSIC',
    SET_ALBUM: 'SET_ALBUM',
    PLAY_LIST: 'PLAY_LIST',
    CURRENT_AUDIO: 'CURRENT_AUDIO',
    LOADING: 'LOADING',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA'
}

export default actionType